;; This "manifest" file can be passed to 'guix package -m' to reproduce
;; the content of your profile.  This is "symbolic": it only specifies
;; package names.  To reproduce the exact same profile, you also need to
;; capture the channels being used, as returned by "guix describe".
;; See the "Replicating Guix" section in the manual.

(specifications->manifest
 (list "nushell"
       "starship"
       "zellij"
       "ripgrep"
       "mise"
       "bat"
       "atuin@18.15"
       "du-dust"
       "zoxide"
       "tldr"
       "fd"
       "ffmpeg"
       "neovim"
       "rsync"
       "git-delta"
       "bottom"
       "github-cli"
       "git-lfs"
       "odt2txt"
       "git"
       "cmake"
       "ninja"
       "ccache"
       "screen"
       "xxhash"
       "expect"
       "tree"
       "jq"
       "python-huggingface-hub"
       "smartmontools"
       "tcpdump"
       "binwalk"
       "pciutils"
       "mpd"
       "parted"
       "gptfdisk"
       "nss-certs"
       "glibc-locales"))
